name: CD

on:
  pull_request:
    branches:
      - main
    types:
      - closed

# Only run when the PR is actually merged (not just closed/rejected)
jobs:
  build:
    name: Build & Push Docker Image
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.short-sha.outputs.short_sha }}
      ecr_registry: ${{ steps.login-ecr.outputs.registry }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set short SHA
        id: short-sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      # Frontend Build
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install frontend dependencies
        working-directory: client
        run: npm ci

      - name: Build frontend
        working-directory: client
        run: npm run generate

      # Copy Build Output to Java Static Resources
      - name: Clear existing static resources
        run: rm -rf server/src/main/resources/static/*

      - name: Copy frontend build to Java static directory
        run: cp -r client/.output/public/. server/src/main/resources/static/

      # Docker Build & Push
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: server
        run: |
          docker buildx build --platform linux/amd64 -t ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.short-sha.outputs.short_sha }} .

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.short-sha.outputs.short_sha }}

  deploy:
    name: Terraform Validate & Apply
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # cache terraform provider  https://github.com/magnetikonline/terraform-github-action-cache-example/blob/main/.github/workflows/example.yaml
      - name: Configure Terraform plugin cache
        run: |
          echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
          mkdir --parents "$HOME/.terraform.d/plugin-cache"

      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: terraform-${{ runner.os }}-


      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        env:
          TF_VAR_image_tag: ${{ needs.build.outputs.image_tag }}
          # these are marked as sensitive variables in tf so they should not appear in logs
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_send_grid_password: ${{ secrets.EMAIL_PASSWORD }}

      - name: Force New Deployment
        run: |
          aws ecs update-service \
            --cluster imagecore-dev-cluster \
            --service imagecore-dev-service \
            --force-new-deployment \
            --region us-east-1